### ISSUE TITLE
wrongly escaped module paths in windows

### ISSUE THREAD

**Issue by lwerdna** [Vector35/deprecated_python_debugger#114]
Note the missing slashes (they were likely treated as escaped) at the end of this trace:

```
Detected local process running at different path: witcher3.exe
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Binary Ninja\plugins\debugger\binjaplug.py", line 382, in apply
    remote_address = self.state.modules.relative_addr_to_absolute(bp)
  File "C:\Users\Me\AppData\Roaming\Binary Ninja\plugins\debugger\binjaplug.py", line 264, in relative_addr_to_absolute
    raise Exception("Cannot resolve relative address: module {} not loaded".format(module))
Exception: Cannot resolve relative address: module C:Program Files (x86)SteamsteamappscommonThe Witcher 3indwitcher3.exe not loaded
```

**Comment by lwerdna** [comment]
It wasn't a string problem (though it is _displayed_ wrong), it's that the process wasn't starting (dll issue) and binja didn't continued to look thru the memory map for module paths, which didn't exist.
