### ISSUE TITLE
opening a raw svg (or other non-executable file) as a hex editor triggers a python exception

### ISSUE THREAD

**Issue by psifertex** [Vector35/deprecated_python_debugger#49]
```Traceback (most recent call last):
  File "/Applications/Binary Ninja-dev.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 227, in _default_is_valid
    return is_valid(view_obj)
  File "/Users/jwiens/Library/Application Support/Binary Ninja/plugins/debugger/ui.py", line 248, in require_adapter
    debug_state = binjaplug.get_state(bv)
  File "/Users/jwiens/Library/Application Support/Binary Ninja/plugins/debugger/binjaplug.py", line 31, in get_state
    state = DebuggerState(bv)
  File "/Users/jwiens/Library/Application Support/Binary Ninja/plugins/debugger/binjaplug.py", line 115, in __init__
    self.memory_view = ProcessView.DebugProcessView(bv)
  File "/Users/jwiens/Library/Application Support/Binary Ninja/plugins/debugger/ProcessView.py", line 26, in __init__
    length = self.memory.perform_get_length()
  File "/Users/jwiens/Library/Application Support/Binary Ninja/plugins/debugger/ProcessView.py", line 134, in perform_get_length
    return (2 ** (self.perform_get_address_size() * 8)) - 1
  File "/Users/jwiens/Library/Application Support/Binary Ninja/plugins/debugger/ProcessView.py", line 126, in perform_get_address_size
    return self.parent_view.arch.address_size
AttributeError: 'NoneType' object has no attribute 'address_size'
```

**Comment by lwerdna** [comment]
If I open even the README.md in this repo I get a crash before `perform_get_address_size()` with no backtrace. Removing the debugger plugin or having DebugProcessView's constructor just return avoids the crash.

**Comment by CouleeApps** [comment]
Fixed as of some time ago.
