### ISSUE TITLE
Debugger UI breaks with version 1.2

### ISSUE THREAD

**Issue by erezto** [Vector35/deprecated_python_debugger#59]
The function binaryninja.binaryview.BinaryView.get_functions_containing in version 1.2 (tested on 1.2.1921) returns None in some cases and thus breaks the debugger's UI.update_highlights function:
Traceback (most recent call last):
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 227, in _default_is_valid
    return is_valid(view_obj)
  File "/Users/someuser/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/ui.py", line 601, in valid_control_pause
    debug_state = binjaplug.get_state(bv)
  File "/Users/someuser/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 35, in get_state
    state = DebuggerState(bv)
  File "/Users/someuser/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 409, in __init__
    self.ui = ui.DebuggerUI(self)
  File "/Users/someuser/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/ui.py", line 37, in __init__
    self.update_highlights()
  File "/Users/someuser/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/ui.py", line 315, in update_highlights
    for func in self.state.bv.get_functions_containing(self.last_ip):
TypeError: 'NoneType' object is not iterable

Potential fix for older versions is verify that the returned value is not None.

**Comment by joshwatson** [comment]
I wouldn't expect them to build out support for old versions of the API

**Comment by psifertex** [comment]
This is actually more of a bug in the plugin manager than anything else. The minimum version supported for the debugger plugin is 2015 which the plugin manager should warn about before letting you install it in the latest stable.

The better fix is to switch to the latest dev since that's where that plugin is intended to run.

I actually just added the minimumVersion check to the plugin manager so this will now be fixed with a warning when you try to install it letting you know it's likely not compatible. (Well, once you're running build 2068 or later. :-) )
