### ISSUE TITLE
"Module not loaded" when debugging a .bndb file

### ISSUE THREAD

**Issue by vijfhoek** [Vector35/deprecated_python_debugger#72]
**Plugin version:** 1.0-beta2
**Binary Ninja version:** 1.3.2015
**Debugged file:** https://crackmes.one/crackme/5d761b6033c5d46f00e2c411
**Operating system:** Windows 10 Pro 1909

When trying to debug an executable on Windows, loaded in Binary Ninja by opening an existing database (.bndb) file, the backslashes in the path seem to be missing:

```
Traceback (most recent call last):
  File "C:\Users\Sijmen\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\dockwidgets\ControlsWidget.py", line 140, in perform_run_thread
    self.debug_state.run()
  File "C:\Users\Sijmen\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\binjaplug.py", line 566, in run
    self.exec()
  File "C:\Users\Sijmen\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\binjaplug.py", line 615, in exec
    self.breakpoints.apply()
  File "C:\Users\Sijmen\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\binjaplug.py", line 372, in apply
    remote_address = self.state.modules.relative_addr_to_absolute(bp)
  File "C:\Users\Sijmen\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\binjaplug.py", line 254, in relative_addr_to_absolute
    raise Exception("Cannot resolve relative address: module {} not loaded".format(module))
Exception: Cannot resolve relative address: module C:UsersSijmenDownloadsCrackMe2.exe not loaded
```

Likely, something went wrong when loading the executable file from the database file.

**EDIT** bv.query_metadata("debugger.breakpoints") returns this:

```
>>> bv.query_metadata("debugger.breakpoints")
[
    {'module': 'C:UsersSijmenDownloadsCrackMe2.exe', 'offset': 7721},
    {'module': 'C:UsersSijmenDownloadsCrackMe2.exe', 'offset': 5024},
    {'module': 'C:\\Users\\Sijmen\\Downloads\\CrackMe2.exe', 'offset': 7721}
]
````

Every time I try to run, save and restart, another backslash-less entry is added

**Comment by lwerdna** [comment]
Thank you for the detailed report. Including the output from `bv.query_metadata("debugger.breakpoints")` is useful.
