### ISSUE TITLE
Importing debugger in headless scripts causes widget-related exceptions

### ISSUE THREAD

**Issue by mechanicalnull** [Vector35/deprecated_python_debugger#82]
Trying to run the sample headless script shows the following exceptions happening (and this is preventing other scripts from working for me also).

```bash
(venv) user@host:~/.binaryninja/plugins/debugger$ /headless.py testbins/md5/md5
Traceback (most recent call last):
  File "/home/user/.binaryninja/plugins/debugger/__init__.py", line 33, in <module>
    from . import binjaplug
  File "/home/user/.binaryninja/plugins/debugger/binjaplug.py", line 17, in <module>
    ui.initialize_ui()
  File "/home/user/.binaryninja/plugins/debugger/ui.py", line 598, in initialize_ui
    widget.register_dockwidget(BreakpointsWidget.DebugBreakpointsWidget, "Debugger Breakpoints", Qt.BottomDockWidgetArea, Qt.Horizontal, False)
  File "/home/user/.binaryninja/plugins/debugger/dockwidgets/widget.py", line 54, in register_dockwidget
    dock_handler.addDockWidget(name, lambda n,p,d: create_widget(widget_class, n, p, d, *args), area, orientation, default_visibility)
AttributeError: 'NoneType' object has no attribute 'addDockWidget'
Traceback (most recent call last):
  File "./headless.py", line 16, in <module>
    from debugger import DebugAdapter, lldb
  File "/home/user/.binaryninja/plugins/debugger/__init__.py", line 33, in <module>
    from . import binjaplug
  File "/home/user/.binaryninja/plugins/debugger/binjaplug.py", line 17, in <module>
    ui.initialize_ui()
  File "/home/user/.binaryninja/plugins/debugger/ui.py", line 598, in initialize_ui
    widget.register_dockwidget(BreakpointsWidget.DebugBreakpointsWidget, "Debugger Breakpoints", Qt.BottomDockWidgetArea, Qt.Horizontal, False)
  File "/home/user/.binaryninja/plugins/debugger/dockwidgets/widget.py", line 54, in register_dockwidget
    dock_handler.addDockWidget(name, lambda n,p,d: create_widget(widget_class, n, p, d, *args), area, orientation, default_visibility)
AttributeError: 'NoneType' object has no attribute 'addDockWidget'
```

Wrapping the `ui.initialize_ui()` block in binjaplug.py with a `if core_ui_enabled():` check seems to fix this, but not sure if that's what you guys want.

Testing on Ubuntu Linux 19.04, core version 1.3.2094-dev, Python 3.7.3 in a virtualenv, debugger repo commit c78b1a89d67c32124da7acbfd25d9fb09a65c9db.

**Comment by lwerdna** [comment]
I tested that the headless.py test script runs on mac and linux with no UI imports or issue, please give it another try.

Related commits:
99382fcfe6488fcfe76e0b2daad355bfaeaf630b 437408e414b6d306711bb66cf2a6f4d9dc39c29d 6612e398d8d86266d4e5f27d4aeffa389392b9d0
