### ISSUE TITLE
Exception when attempting to use debugger

### ISSUE THREAD

**Issue by CunningLogic** [Vector35/deprecated_python_debugger#95]
Version 2.0.2133-dev (Build ID a037596e)

commit a044997d315eb6a91777b4acc836f51cf487ce52 (HEAD -> master, tag: 1.0, origin/master, origin/HEAD)
Author: Jordan Wiens <jordan@psifertex.com>
Date:   Wed May 6 22:12:49 2020 -0400

    1.0 release

Traceback (most recent call last):
  File "/home/jcase/bin/binaryninja/plugins/../python/binaryninja/binaryview.py", line 2033, in _read
    data = self.perform_read(offset, length)
  File "/home/jcase/.binaryninja/plugins/debugger/ProcessView.py", line 167, in perform_read
    batch = adapter.mem_read(block, cache_len)
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 186, in mem_read
    return self.submit(lambda: self.adapter.mem_read(address, length))
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 84, in submit
    raise result
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 41, in perform_task
    self.results[index] = (True, job())
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 186, in <lambda>
    return self.submit(lambda: self.adapter.mem_read(address, length))
  File "/home/jcase/.binaryninja/plugins/debugger/gdblike.py", line 352, in mem_read
    reply = self.rspConn.tx_rx('m%x,%x' % (address, sz))
AttributeError: 'NoneType' object has no attribute 'tx_rx'
Traceback (most recent call last):
  File "/home/jcase/.binaryninja/plugins/debugger/dockwidgets/ControlsWidget.py", line 184, in perform_run_thread
    self.debug_state.run()
  File "/home/jcase/.binaryninja/plugins/debugger/binjaplug.py", line 600, in run
    self.exec()
  File "/home/jcase/.binaryninja/plugins/debugger/binjaplug.py", line 647, in exec
    raise e
  File "/home/jcase/.binaryninja/plugins/debugger/binjaplug.py", line 642, in exec
    self.adapter.exec(fpath, self.command_line_args)
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 124, in exec
    return self.submit(lambda: self.adapter.exec(path, args))
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 84, in submit
    raise result
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 41, in perform_task
    self.results[index] = (True, job())
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 124, in <lambda>
    return self.submit(lambda: self.adapter.exec(path, args))
  File "/home/jcase/.binaryninja/plugins/debugger/gdb.py", line 51, in exec
    self.connect('localhost', port)
  File "/home/jcase/.binaryninja/plugins/debugger/gdb.py", line 78, in connect
    self.connect_continued(sock, rspConn)
  File "/home/jcase/.binaryninja/plugins/debugger/gdb.py", line 55, in connect_continued
    self.rspConn = connection
NameError: name 'connection' is not defined
[Errno 98] Address already in use
/usr/bin/gdbserver --once --no-startup-with-shell localhost:31338 /storage/CTFSolutions/ctf/pico2018/echoback/echoback
Traceback (most recent call last):
  File "/home/jcase/.binaryninja/plugins/debugger/dockwidgets/ControlsWidget.py", line 184, in perform_run_thread
    self.debug_state.run()
  File "/home/jcase/.binaryninja/plugins/debugger/binjaplug.py", line 600, in run
    self.exec()
  File "/home/jcase/.binaryninja/plugins/debugger/binjaplug.py", line 647, in exec
    raise e
  File "/home/jcase/.binaryninja/plugins/debugger/binjaplug.py", line 642, in exec
    self.adapter.exec(fpath, self.command_line_args)
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 124, in exec
    return self.submit(lambda: self.adapter.exec(path, args))
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 84, in submit
    raise result
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 41, in perform_task
    self.results[index] = (True, job())
  File "/home/jcase/.binaryninja/plugins/debugger/QueuedAdapter.py", line 124, in <lambda>
    return self.submit(lambda: self.adapter.exec(path, args))
  File "/home/jcase/.binaryninja/plugins/debugger/gdb.py", line 51, in exec
    self.connect('localhost', port)
  File "/home/jcase/.binaryninja/plugins/debugger/gdb.py", line 78, in connect
    self.connect_continued(sock, rspConn)
  File "/home/jcase/.binaryninja/plugins/debugger/gdb.py", line 55, in connect_continued
    self.rspConn = connection
NameError: name 'connection' is not defined

**Comment by CouleeApps** [comment]
Fixed by #90
